- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Remove app dir
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating app dir
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes


