---
- name: setting up mongodb server
  hosts: all
  become: true
  vars:
    db_type: mongo

  tasks:
    - name: removing repo files
      ansible.builtin.import_tasks:
        file: copy_and_remove_Repo_files.yml

    - name: installling mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: Replace the ip address to 0.0.0.0
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Restart mongodb
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: yes





#
#starting_enabling_without_daemon
