---
- name: setting up shipping server
  hosts: all
  become: true
  vars:
    component: shipping
    db_type: mysql

  tasks:
    - name: setting up shipping server calling maven java function
      ansible.builtin.import_tasks:
        file: maven_java.yml


