---
- name: setting up user server
  hosts: all
  become: true
  vars:
    component: user
    db_type: mongo

  tasks:
    - name: setting up user server calling nodejs function
      ansible.builtin.import_tasks:
        file: nodejs.yml


