- name: copy_and_remove_Repo_files
  ansible.builtin.import_tasks:
    file: copy_and_remove_Repo_files.yml

- name: downloading mongodb server and installing
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: navigating to  app dir
  ansible.builtin.file:
    path: /app

- name: SETTING UP SCHEMA
  ansible.builtin.shell: mongo --host mongodb.nareshdevops.cloud </app/schema/{{component}}.js
      
