- name: copying and removing service files by using import module
  ansible.builtin.import_tasks:
    file: copy_and_remove_files.yml


- name: downloading nodejs and installing
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: downloading nodejs and installing
  ansible.builtin.yum:
    name: nodejs
    state: installed


- name: adding user and downloading Code also unzip
  ansible.builtin.import_tasks:
    file: adduser_downloadCode_unzip.yml


- name: changing directory to /app
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Setting up {{ db_type }}
  import_tasks: db_schema_setup.yml
  when: db_type is defined


- name: restarting and enabling {{component}}
  ansible.builtin.import_tasks:
    file: restarting_enabling_service.yml
